# Makefile for library librsb2_core.so
# @file src/rsb2/rsb2_libcore/makefile

TARGET := lib/librsb2_os.so
DEPENDS := 
LIBS := 
DIR_NAME := rsb2/rsb2_libos
TEST_NAME := rsb2_test_libcore
TEST_LIBS := -lrsb2_os

include ../rsb2_common.mk

## END ##
